---
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.31.0
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
    QUERY_DEFAULTS_LIMIT: 25
    AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
    PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    ENABLE_MODULES: ""
    DEFAULT_VECTORIZER_MODULE: "none"
    CLUSTER_HOSTNAME: "bca_bot"
    VECTOR_INDEX_TYPE: hnsw
    VECTOR_INDEX_CONFIG: >
      {
        "efConstruction": 128,
        "maxConnections": 64,
        "ef": 32
      }
  restart: unless-stopped
volumes:
  weaviate_data:
...